In [1]:
import pandas as pd

In [2]:
polling_df = pd.read_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/preprocessed_polling.csv')
polling_df

,year,national_con_pre_ge,national_lab_pre_ge,national_lib_pre_ge,national_oth_pre_ge
0,1987,0.428,0.341,0.214,0.017
1,1992,0.377,0.390,0.196,0.037
2,1997,0.309,0.493,0.134,0.064
3,2001,0.314,0.449,0.177,0.060
4,2005,0.326,0.375,0.228,0.071
5,2010,0.358,0.281,0.270,0.091
6,2015,0.336,0.334,0.092,0.238
7,2017,0.429,0.368,0.077,0.126
8,2019,0.431,0.332,0.120,0.117

In [3]:
election_results_df = pd.read_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/preprocessed_election_result.csv')
election_results_df

,year,constituency_id,constituency_name,country/region,total_votes,con_votes,lab_votes,lib_votes,oth_votes,con_share,lab_share,lib_share,oth_share,con_share_prev,lab_share_prev,lib_share_prev,oth_share_prev
0,2010,W07000049,Aberavon,Wales,30958,4411.0,16073.0,5034.0,5440.0,0.142,0.519,0.163,0.176,0.102,0.600,0.138,0.160
1,2010,W07000058,Aberconwy,Wales,29966,10734.0,7336.0,5786.0,6110.0,0.358,0.245,0.193,0.204,0.279,0.371,0.200,0.150
2,2010,S14000001,Aberdeen North,Scotland,37701,4666.0,16746.0,7001.0,9288.0,0.124,0.444,0.186,0.246,0.094,0.425,0.239,0.242
3,2010,S14000002,Aberdeen South,Scotland,43034,8914.0,15722.0,12216.0,6182.0,0.207,0.365,0.284,0.144,0.171,0.367,0.335,0.127
4,2010,S14000003,Airdrie & Shotts,Scotland,35849,3133.0,20849.0,2898.0,8969.0,0.087,0.582,0.081,0.250,0.099,0.590,0.114,0.196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2582,2019,E14001059,Wythenshawe & Sale East,North West,44759,13459.0,23855.0,3111.0,4334.0,0.301,0.533,0.070,0.097,0.296,0.622,0.033,0.049
2583,2019,E14001060,Yeovil,South West,59260,34588.0,3761.0,18407.0,2504.0,0.584,0.063,0.311,0.042,0.545,0.125,0.297,0.033
2584,2019,W07000041,Ynys Mon,Wales,36552,12959.0,10991.0,0.0,12602.0,0.355,0.301,0.000,0.345,0.278,0.419,0.013,0.291
2585,2019,E14001061,York Central,Yorkshire and The Humber,49505,13767.0,27312.0,4149.0,4277.0,0.278,0.552,0.084,0.086,0.302,0.652,0.047,0.000
2586,2019,E14001062,York Outer,Yorkshire and The Humber,55347,27324.0,17339.0,9992.0,692.0,0.494,0.313,0.181,0.013,0.511,0.367,0.103,0.019

In [4]:
elections_polling_df = election_results_df.merge(polling_df, on='year', how='left')
elections_polling_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2587 entries, 0 to 2586
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 2587 non-null   int64
 1   constituency_id      2587 non-null   object
 2   constituency_name    2587 non-null   object
 3   country/region       2587 non-null   object
 4   total_votes          2587 non-null   int64
 5   con_votes            2587 non-null   float64
 6   lab_votes            2587 non-null   float64
 7   lib_votes            2587 non-null   float64
 8   oth_votes            2587 non-null   float64
 9   con_share            2587 non-null   float64
 10  lab_share            2587 non-null   float64
 11  lib_share            2587 non-null   float64
 12  oth_share            2587 non-null   float64
 13  con_share_prev       2587 non-null   float64
 14  lab_share_prev       2587 non-null   float64
 15  lib_share_prev       2587 non-null   float64
 16  oth_share_prev       2587 non-null   float64
 17  national_con_pre_ge  2587 non-null   float64
 18  national_lab_pre_ge  2587 non-null   float64
 19  national_lib_pre_ge  2587 non-null   float64
 20  national_oth_pre_ge  2587 non-null   float64
dtypes: float64(16), int64(2), object(3)
memory usage: 444.6+ KB

In [5]:
# Feature engineer polling data at constituency level
elections_polling_df['national_con_pre_ge'].groupby(elections_polling_df['year']).mean()

year
2010    0.358
2015    0.336
2017    0.429
2019    0.431
Name: national_con_pre_ge, dtype: float64

In [6]:
# Feature engineer polling data at constituency level
elections_polling_df['mean_con_share_pre_ge'] = elections_polling_df.groupby('year')['con_share_prev'].transform('mean')
elections_polling_df['mean_lab_share_pre_ge'] = elections_polling_df.groupby('year')['lab_share_prev'].transform('mean')
elections_polling_df['mean_lib_share_pre_ge'] = elections_polling_df.groupby('year')['lib_share_prev'].transform('mean')
elections_polling_df['mean_oth_share_pre_ge'] = elections_polling_df.groupby('year')['oth_share_prev'].transform('mean')

In [9]:
elections_polling_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2587 entries, 0 to 2586
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   2587 non-null   int64
 1   constituency_id        2587 non-null   object
 2   constituency_name      2587 non-null   object
 3   country/region         2587 non-null   object
 4   total_votes            2587 non-null   int64
 5   con_votes              2587 non-null   float64
 6   lab_votes              2587 non-null   float64
 7   lib_votes              2587 non-null   float64
 8   oth_votes              2587 non-null   float64
 9   con_share              2587 non-null   float64
 10  lab_share              2587 non-null   float64
 11  lib_share              2587 non-null   float64
 12  oth_share              2587 non-null   float64
 13  con_share_prev         2587 non-null   float64
 14  lab_share_prev         2587 non-null   float64
 15  lib_share_prev         2587 non-null   float64
 16  oth_share_prev         2587 non-null   float64
 17  national_con_pre_ge    2587 non-null   float64
 18  national_lab_pre_ge    2587 non-null   float64
 19  national_lib_pre_ge    2587 non-null   float64
 20  national_oth_pre_ge    2587 non-null   float64
 21  mean_con_share_pre_ge  2587 non-null   float64
 22  mean_lab_share_pre_ge  2587 non-null   float64
 23  mean_lib_share_pre_ge  2587 non-null   float64
 24  mean_oth_share_pre_ge  2587 non-null   float64
dtypes: float64(20), int64(2), object(3)
memory usage: 525.5+ KB

In [12]:
elections_polling_df['con_pre_ge_adjusted'] = elections_polling_df['con_share_prev']/elections_polling_df['mean_con_share_pre_ge']*elections_polling_df['national_con_pre_ge']
elections_polling_df['lab_pre_ge_adjusted'] = elections_polling_df['lab_share_prev']/elections_polling_df['mean_con_share_pre_ge']*elections_polling_df['national_con_pre_ge']
elections_polling_df['lib_pre_ge_adjusted'] = elections_polling_df['lib_share_prev']/elections_polling_df['mean_con_share_pre_ge']*elections_polling_df['national_con_pre_ge']
elections_polling_df['oth_pre_ge_adjusted'] = elections_polling_df['oth_share_prev']/elections_polling_df['mean_con_share_pre_ge']*elections_polling_df['national_con_pre_ge']

In [15]:
# Display maximum columns
pd.set_option('display.max_columns', None)
elections_polling_df.head()

,year,constituency_id,constituency_name,country/region,total_votes,con_votes,lab_votes,lib_votes,oth_votes,con_share,lab_share,lib_share,oth_share,con_share_prev,lab_share_prev,lib_share_prev,oth_share_prev,national_con_pre_ge,national_lab_pre_ge,national_lib_pre_ge,national_oth_pre_ge,mean_con_share_pre_ge,mean_lab_share_pre_ge,mean_lib_share_pre_ge,mean_oth_share_pre_ge,con_pre_ge_adjusted,lab_pre_ge_adjusted,lib_pre_ge_adjusted,oth_pre_ge_adjusted
0,2010,W07000049,Aberavon,Wales,30958,4411.0,16073.0,5034.0,5440.0,0.142,0.519,0.163,0.176,0.102,0.600,0.138,0.160,0.358,0.281,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.118590,0.697587,0.160445,0.186023
1,2010,W07000058,Aberconwy,Wales,29966,10734.0,7336.0,5786.0,6110.0,0.358,0.245,0.193,0.204,0.279,0.371,0.200,0.150,0.358,0.281,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.324378,0.431342,0.232529,0.174397
2,2010,S14000001,Aberdeen North,Scotland,37701,4666.0,16746.0,7001.0,9288.0,0.124,0.444,0.186,0.246,0.094,0.425,0.239,0.242,0.358,0.281,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.109289,0.494124,0.277872,0.281360
3,2010,S14000002,Aberdeen South,Scotland,43034,8914.0,15722.0,12216.0,6182.0,0.207,0.365,0.284,0.144,0.171,0.367,0.335,0.127,0.358,0.281,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.198812,0.426691,0.389486,0.147656
4,2010,S14000003,Airdrie & Shotts,Scotland,35849,3133.0,20849.0,2898.0,8969.0,0.087,0.582,0.081,0.250,0.099,0.590,0.114,0.196,0.358,0.281,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.115102,0.685961,0.132542,0.227879

In [16]:
# Save to csv
elections_polling_df.to_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/election_polling_joined.csv', index=False)