In [3]:
import pandas as pd

In [7]:
# Import census data
census_df = pd.read_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/preprocessed_interpolated_census_data.csv')
census_df.head()

,constituency_name,constituency_id,year,0-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80+,Home_owners,Private_renters,Social_renters,Asian,Black,Mixed,Other,White
0,Aberavon,W07000049,2010,0.1068,0.1242,0.1227,0.1246,0.1446,0.1311,0.1149,0.0778,0.0528,0.686902,0.109669,0.203430,0.011438,0.002786,0.006774,0.001085,0.977918
1,Aberavon,W07000049,2011,0.1082,0.1203,0.1227,0.1256,0.1413,0.1334,0.1168,0.0786,0.0528,0.683026,0.113468,0.203506,0.012505,0.002964,0.007334,0.001331,0.975867
2,Aberavon,W07000049,2012,0.1096,0.1164,0.1227,0.1266,0.1380,0.1357,0.1187,0.0794,0.0528,0.679151,0.117268,0.203581,0.013573,0.003142,0.007893,0.001577,0.973816
3,Aberavon,W07000049,2013,0.1110,0.1125,0.1227,0.1276,0.1347,0.1380,0.1206,0.0802,0.0528,0.675276,0.121067,0.203657,0.014640,0.003320,0.008453,0.001823,0.971764
4,Aberavon,W07000049,2014,0.1121,0.1105,0.1242,0.1273,0.1310,0.1403,0.1210,0.0809,0.0528,0.671401,0.124867,0.203733,0.015708,0.003497,0.009013,0.002069,0.969713

In [8]:
# Import eelction/pollig data
election_polling_df = pd.read_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/election_polling_joined.csv')
election_polling_df.head()

,year,constituency_id,constituency_name,country/region,total_votes,con_votes,lab_votes,lib_votes,oth_votes,con_share,...,national_lib_pre_ge,national_oth_pre_ge,mean_con_share_pre_ge,mean_lab_share_pre_ge,mean_lib_share_pre_ge,mean_oth_share_pre_ge,con_pre_ge_adjusted,lab_pre_ge_adjusted,lib_pre_ge_adjusted,oth_pre_ge_adjusted
0,2010,W07000049,Aberavon,Wales,30958,4411.0,16073.0,5034.0,5440.0,0.142,...,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.118590,0.697587,0.160445,0.186023
1,2010,W07000058,Aberconwy,Wales,29966,10734.0,7336.0,5786.0,6110.0,0.358,...,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.324378,0.431342,0.232529,0.174397
2,2010,S14000001,Aberdeen North,Scotland,37701,4666.0,16746.0,7001.0,9288.0,0.124,...,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.109289,0.494124,0.277872,0.281360
3,2010,S14000002,Aberdeen South,Scotland,43034,8914.0,15722.0,12216.0,6182.0,0.207,...,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.198812,0.426691,0.389486,0.147656
4,2010,S14000003,Airdrie & Shotts,Scotland,35849,3133.0,20849.0,2898.0,8969.0,0.087,...,0.27,0.091,0.307918,0.365126,0.215917,0.110826,0.115102,0.685961,0.132542,0.227879

In [13]:
# Merge the dfs
final_df = pd.merge(census_df, election_polling_df, on=['constituency_id', 'year'])
final_df.rename(columns={'constituency_name_x': 'constituency_name'}, inplace=True)
final_df.drop(columns=['constituency_name_y'], inplace=True)

In [16]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2279 entries, 0 to 2278
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   constituency_name      2279 non-null   object
 1   constituency_id        2279 non-null   object
 2   year                   2279 non-null   int64
 3   0-9                    2279 non-null   float64
 4   10-19                  2279 non-null   float64
 5   20-29                  2279 non-null   float64
 6   30-39                  2279 non-null   float64
 7   40-49                  2279 non-null   float64
 8   50-59                  2279 non-null   float64
 9   60-69                  2279 non-null   float64
 10  70-79                  2279 non-null   float64
 11  80+                    2279 non-null   float64
 12  Home_owners            2279 non-null   float64
 13  Private_renters        2279 non-null   float64
 14  Social_renters         2279 non-null   float64
 15  Asian                  2279 non-null   float64
 16  Black                  2279 non-null   float64
 17  Mixed                  2279 non-null   float64
 18  Other                  2279 non-null   float64
 19  White                  2279 non-null   float64
 20  country/region         2279 non-null   object
 21  total_votes            2279 non-null   int64
 22  con_votes              2279 non-null   float64
 23  lab_votes              2279 non-null   float64
 24  lib_votes              2279 non-null   float64
 25  oth_votes              2279 non-null   float64
 26  con_share              2279 non-null   float64
 27  lab_share              2279 non-null   float64
 28  lib_share              2279 non-null   float64
 29  oth_share              2279 non-null   float64
 30  con_share_prev         2279 non-null   float64
 31  lab_share_prev         2279 non-null   float64
 32  lib_share_prev         2279 non-null   float64
 33  oth_share_prev         2279 non-null   float64
 34  national_con_pre_ge    2279 non-null   float64
 35  national_lab_pre_ge    2279 non-null   float64
 36  national_lib_pre_ge    2279 non-null   float64
 37  national_oth_pre_ge    2279 non-null   float64
 38  mean_con_share_pre_ge  2279 non-null   float64
 39  mean_lab_share_pre_ge  2279 non-null   float64
 40  mean_lib_share_pre_ge  2279 non-null   float64
 41  mean_oth_share_pre_ge  2279 non-null   float64
 42  con_pre_ge_adjusted    2279 non-null   float64
 43  lab_pre_ge_adjusted    2279 non-null   float64
 44  lib_pre_ge_adjusted    2279 non-null   float64
 45  oth_pre_ge_adjusted    2279 non-null   float64
dtypes: float64(41), int64(2), object(3)
memory usage: 836.8+ KB