In [3]:
import pandas as pd

In [59]:
input_polling_df = pd.read_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/monthly_polling_data.csv')

In [60]:
input_polling_df

,Year,Month,Conservative,Unnamed: 3,Labour,Unnamed: 5,LD,Unnamed: 7,UKIP,Unnamed: 9,...,Green,Unnamed: 16,Unnamed: 17,Lead,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,1983.0,GE,43.5,NaN,28.3,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,15.2,NaN,NaN,NaN,NaN,NaN,NaN
1,1983.0,Jun-83,43.0,NaN,27.0,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jul-83,44.8,1.8,28.6,1.6,25.1,-3.9,NaN,NaN,...,NaN,NaN,NaN,16.2,0.2,NaN,NaN,NaN,NaN,NaN
3,NaN,Aug-83,45.7,0.8,27.4,-1.3,25.5,0.4,NaN,NaN,...,NaN,NaN,NaN,18.3,2.1,NaN,NaN,NaN,NaN,NaN
4,NaN,Sep-83,45.5,-0.1,26.7,-0.7,26.3,0.7,NaN,NaN,...,NaN,NaN,NaN,18.9,0.6,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,NaN,Aug-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,NaN,Sep-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,NaN,Oct-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,NaN,Nov-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,NaN,Dec-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# We need the polling data BEFORE GENERAL ELECTON!
input_polling_df['Year'] = input_polling_df['Year'].ffill().astype(int)
input_polling_df.head()

,Year,Month,Conservative,Unnamed: 3,Labour,Unnamed: 5,LD,Unnamed: 7,UKIP,Unnamed: 9,...,Green,Unnamed: 16,Unnamed: 17,Lead,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,1983,GE,43.5,NaN,28.3,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,15.2,NaN,NaN,NaN,NaN,NaN,NaN
1,1983,Jun-83,43.0,NaN,27.0,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1983,Jul-83,44.8,1.8,28.6,1.6,25.1,-3.9,NaN,NaN,...,NaN,NaN,NaN,16.2,0.2,NaN,NaN,NaN,NaN,NaN
3,1983,Aug-83,45.7,0.8,27.4,-1.3,25.5,0.4,NaN,NaN,...,NaN,NaN,NaN,18.3,2.1,NaN,NaN,NaN,NaN,NaN
4,1983,Sep-83,45.5,-0.1,26.7,-0.7,26.3,0.7,NaN,NaN,...,NaN,NaN,NaN,18.9,0.6,NaN,NaN,NaN,NaN,NaN

In [24]:
pre_GE_rows = input_polling_df.loc[input_polling_df['Month'] == 'GE'].index -1
input_polling_df.loc[pre_GE_rows[1:]] #remove the first one

# Assuming df is your DataFrame
# Get a list of columns that contain the substring 'Unnamed'
unnamed_columns = [col for col in input_polling_df.columns if 'Unnamed' in col]

# Drop the columns with the specified names
input_polling_df = input_polling_df.drop(columns=unnamed_columns)

In [28]:
input_polling_df = input_polling_df.loc[pre_GE_rows[1:]] #remove the first one
input_polling_df.fillna(0, inplace=True)

In [31]:
input_polling_df.drop(columns=['Lead'], inplace=True)

KeyError: "['Lead'] not found in axis"

In [47]:
# Identify columns with float dtype (assuming percentage columns are floats)
percentage_columns = input_polling_df.select_dtypes(include='float64').columns

# Divide columns by 100 if they are percentage columns
input_polling_df[percentage_columns] = input_polling_df[percentage_columns] / 100

In [57]:
input_polling_df['oth_pre_ge'] = 1.0 - input_polling_df['Conservative'] - input_polling_df['Labour'] - input_polling_df['LD']

In [58]:
input_polling_df

   index  Year  Conservative  Labour     LD  oth_pre_ge
0      0  1987         0.428   0.341  0.214       0.017
1      1  1992         0.377   0.390  0.196       0.037
2      2  1997         0.309   0.493  0.134       0.064
3      3  2001         0.314   0.449  0.177       0.060
4      4  2005         0.326   0.375  0.228       0.071
5      5  2010         0.358   0.281  0.270       0.091
6      6  2015         0.336   0.334  0.092       0.238
7      7  2017         0.429   0.368  0.077       0.126
8      8  2019         0.431   0.332  0.120       0.117

In [81]:
# Put all the code in a function
def preprocess_polling_data(polling_df):
    cleaned_polling_df = polling_df.copy()
    # fill the missing values for year
    cleaned_polling_df['Year'] = cleaned_polling_df['Year'].ffill().astype(int)
    # Take the rows before the general election
    pre_GE_rows = cleaned_polling_df.loc[cleaned_polling_df['Month'] == 'GE'].index -1
    cleaned_polling_df = cleaned_polling_df.loc[pre_GE_rows[1:]]
    # Identify columns with float dtype (assuming percentage columns are floats)
    percentage_columns = cleaned_polling_df.select_dtypes(include='float64').columns
    # Divide columns by 100 if they are percentage columns
    cleaned_polling_df[percentage_columns] = cleaned_polling_df[percentage_columns] / 100
    # Calculate shate for the other parties
    cleaned_polling_df['oth_pre_ge'] = 1.0 - cleaned_polling_df['Conservative'] - cleaned_polling_df['Labour'] - cleaned_polling_df['LD']
    cleaned_polling_df = cleaned_polling_df[['Year', 'Conservative', 'Labour', 'LD', 'oth_pre_ge']].reset_index(drop=True)
    cleaned_polling_df.columns = ["year", "national_con_pre_ge", "national_lab_pre_ge", "national_lib_pre_ge", "national_oth_pre_ge"]
    return cleaned_polling_df

In [82]:
preprocess_polling_data = preprocess_polling_data(input_polling_df)
preprocess_polling_data

,year,national_con_pre_ge,national_lab_pre_ge,national_lib_pre_ge,national_oth_pre_ge
0,1987,0.428,0.341,0.214,0.017
1,1992,0.377,0.390,0.196,0.037
2,1997,0.309,0.493,0.134,0.064
3,2001,0.314,0.449,0.177,0.060
4,2005,0.326,0.375,0.228,0.071
5,2010,0.358,0.281,0.270,0.091
6,2015,0.336,0.334,0.092,0.238
7,2017,0.429,0.368,0.077,0.126
8,2019,0.431,0.332,0.120,0.117

In [83]:
preprocess_polling_data.to_csv('/Users/andreabrumana/code/willgreen93/UK_election/raw_data/preprocessed/preprocessed_polling.csv', index=False)